name: Build TC

on:
  workflow_dispatch:
  schedule:
    - cron: '17 0 * * *' 

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Build TC
        run: |
          wget https://raw.githubusercontent.com/mornye1517/Android-CI/main/Common/clang.sh
          bash clang.sh

        env:
          LLVM_NAME: ${{ secrets.LLVM_NAME }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
